# Generated by Django 5.2.6 on 2026-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The original note text entered by the user')),
                ('summary', models.TextField(blank=True, default='', help_text='AI-generated summary of the note')),
                ('keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords extracted via TF-IDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this note was created')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
